# Common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    logging:
        logstash:
            enabled: true
            host: 192.168.99.100 # If using a Virtual Machine on Mac OS X or Windows with docker-machine, use the Docker's host IP here
            port: 5005
            queueSize: 512  
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                    

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
